### PR TITLE
Update to Unified Build controls

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
Hold on this, validating locally.

**Comment by mmitche** [comment]
Resolves https://github.com/dotnet/test-templates/issues/246

**Comment by mmitche** [comment]
@dotnet/source-build-internal

**Review by Evangelink — APPROVED** [review]

**Comment by Evangelink** [comment]
Let us know when we have greenlight for merging this.

**Review by MichaelSimons — APPROVED** [review]

**Comment by Evangelink** [comment]
@mmitche Do you need more reviews or can I proceed with merging the changes?

**Comment by mmitche** [comment]
Hold please, still verifying.

**Comment by mmitche** [comment]
Looking good on latest builds, merging.

**Pull request merged**
