### PR TITLE
Updating NUnit template to use NUnit3TestAdapter version 4.3.1

### PR DESCRIPTION
**Pull request by OsirisTerje**

### CODE REVIEW

**Comment by MarcoRossignoli** [comment]
@OsirisTerje can you rebase the main and update also the 8.0 template so we can merge?

**Comment by MarcoRossignoli** [comment]
Hi @OsirisTerje I'm going to close this one because we're changing templating versioning strategy, we will bump the version when we will have the final plan. Thanks for your help!

**Comment by OsirisTerje** [comment]
@MarcoRossignoli  The NUnit template is now very much outdated.  It uses Test.sdk 17.3.2, it uses adapter 4.2.1, the other packages also are outdated.  
I was going in here now to raise another PR for the adapter 4.4.2 version, and noticed this closed PR.  I think it is better to accept the PRs **UNTIL** you have another plan and have started to act on that.  
If this is too hard, it is better that this template is moved back to the NUnit project, we can release more often.  Will that help you?

**Comment by MarcoRossignoli** [comment]
@OsirisTerje it's fine to bump but only for version > 6.0(so 6.0,7.0,8.0) for now, if you open the PR we can merge it.

**Comment by Evangelink** [comment]
To give some more context, we have noticed that there is an issue with the insertion and the template changes have been inserted in all recent servicing which could potentially cause some issue (e.g. big bump of some version in a patch of netcoreapp3.1). We are investigating/fixing the issue as we speak but in the meantime we had to prevent insertions.

**Comment by OsirisTerje** [comment]
Ok, thanks!   I'll raise a new PR for the latest

**Pull request closed without merging**
