### PR TITLE
Template update 13.05.2021

### PR DESCRIPTION
**Pull request by cvpoienaru**
Template update 13.05.2021

### CODE REVIEW

**Review by jakubch1 — APPROVED** [review]
Why there is no 16.7.1 changed anywhere?

**Comment by cvpoienaru** [comment]
> Why there is no 16.7.1 changed anywhere?

You mean for `Microsoft.NET.Test.Sdk` package ? There's no reference of a `16.7.1` version in this repo for this package, only `16.8.3` before the change and `16.9.4` afterwards. Do you remember which templates in particular had version `16.7.1` ?

**Comment by jakubch1** [comment]
Mstest and xunit

**Comment by Sanan07** [comment]
Just for my information, it is interesting, how is your last commit fixed that pipeline issue, which mentioned some old Nuget versions?

**Comment by Sanan07** [comment]
It was updated to 16.8.3 but not inserted to VS, that why in VS now we have only 16.7.1 Test.SDK. 
I just checked in Preview 3 and got 16.7.1.

**Review by Sanan07 — APPROVED** [review]

**Comment by cvpoienaru** [comment]
> Just for my information, it is interesting, how is your last commit fixed that pipeline issue, which mentioned some old Nuget versions?

Oh, I was looking in the pipeline and it appeared as if all projects failed on `dotnet restore` for projects containing both `coverlet` and `NUnit` references, and there were suggestions of which package versions to use instead.

image

**Pull request merged**
