### PR TITLE
NUnit updates to latest packages

### PR DESCRIPTION
**Pull request by OsirisTerje**
Updated all NUnit templates to use NUnit 4.0.1, NUnit3TestAdapter 4.5.0, NUnit.Analyzer to 3.10.0, and test sdk to version 17.8.0, and coverlet to version 6.0.0.

### CODE REVIEW

**Comment by OsirisTerje** [comment]
@Evangelink These should have been upgraded when dotnet 8 was released. They have been lagging for quite some time now. 

Not updating them would also cause more issues, particularly with the support for .net 8 and upwards.   One thing is targeting a particular dotnet version, another is running under a dotnet version.  And, right now we are forced to upgrade an earlier adapter because the embedded engine could not run under dotnet 8, while targeting net45. 
So **not** upgrading the template can cause more issues than upgrading them.

Also, I can't see why these templates should be locked to the dotnet releases.

**Comment by Evangelink** [comment]
I have created a PR (see #334) to bump version for templates in .NET 8 and .NET 9. For .NET 8, I will present the case to the tactics commitee to get their approval.

> Also, I can't see why these templates should be locked to the dotnet releases.

Templates are inserted in .NET SDK in each version. Bumping to major version in bug fix update of SDK means that we could lead to breaks on users. This can be seen as limiting but this is how it is.

**Comment by OsirisTerje** [comment]
@Evangelink I find this very unfortunate. When people update NUnit, they would also expect new projects to be at the same level.   And at least they would expect to be able to update the template tool. 
It doesn't make sense to bind this to an unrelated SDK version.  

For versions that are not supported anymore, like netcore 2.1 and 3.1, they can stay as they are - and the PR didnt change anything lower than net 6.

**Comment by Evangelink** [comment]
I understand your perception and .NET SDK insertions do put many constraint on us but we are not deciding how it works. All I can say for sure is that we should only update moving forward and don't touch the past except if there is a critical bug.

**Comment by OsirisTerje** [comment]
> we should only update moving forward

Can we then change it in the dotnet version 9 template ?

**Comment by Evangelink** [comment]
Hi @OsirisTerje, see https://github.com/dotnet/test-templates/pull/343

**Comment by rextor92** [comment]
There is user feedback that the official documentation is showing outdated NUnit code, logged in dotnet/docs#40080.

It seems @OsirisTerje has already updated the samples in the docs repo back in December which caused tutorial pages to show both NUnit3 and NUnit4 source code - [example](https://learn.microsoft.com/en-gb/dotnet/core/testing/unit-testing-with-nunit). I volunteered to work on that issue and proceeded to update the samples repo before I realized this template is out of date and went down the rabbit hole until I finally found this 😄 

I echo Terje's opinion - starting a brand new project that immediately introduces breaking changes upon updating the packages is very unfortunate. A tutorial referencing outdated framework makes no sense either. I can maybe add a paragraph or two for updating NUnit in the C#, VB and F# articles and we'll need to remove it once #343 and #350 goes live. (cc @IEvangelist)

@Evangelink can you confirm the .NET 8 package version bump isn't going live until .NET 9 in November?

**Comment by Evangelink** [comment]
Ok so I was wrong (I am taking over the repo and I don't have all the pieces/interactions clear in my head). For some reason, we still have the net8.0 templates in the repo but the insertion into net8 installer is disabled.

As for net9.0, this is already part of the preview and so will be part of the first official release of net9.0

**Pull request closed without merging**
