### PR TITLE
update pkg for selenium.webdriver

### PR DESCRIPTION
**Pull request by yanlingwang23**
Update Edgedriver template for .NET to use the latest Selenium.WebDriver nuget package.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/test-templates?pullRequest=239) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/test-templates?pullRequest=239) before we can accept your contribution.<br/><br/>:x: yanlingwang23 [sign now](https://cla.dotnetfoundation.org/dotnet/test-templates?pullRequest=239)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/test-templates?pullRequest=239) it.</sub>

**Comment by bwalderman** [comment]
Please also update this comment in EdgeDriverTest.cs (both versions):

```
// please follow the instructions from http://go.microsoft.com/fwlink/?LinkId=619687
// to install Microsoft WebDriver.
```

The old link appears to be broken. Please update it to https://docs.microsoft.com/en-us/microsoft-edge/webdriver-chromium

Please also update "Microsoft WebDriver" to "Microsoft Edge WebDriver".

**Comment by bwalderman** [comment]
Can you also update the `<DisplayName>` in both of the .vsixmanifest files? "Web Driver" should be "WebDriver" (no space). Thanks!

**Review by bwalderman — APPROVED** [review]

**Review by cvpoienaru — APPROVED** [review]
LGTM, approved !

**Pull request merged**
