### PR TITLE
Onboard to v3 publishing

### PR DESCRIPTION
**Pull request by mmitche**

### CODE REVIEW

**Comment by mmitche** [comment]
Also update arcade

**Comment by mmitche** [comment]
@nohwnd This fixes errors in the staging pipeline. It needs an update to a newer arcade. I'd like to have this in for VS 16.8 and .NET 5 RTM

**Comment by nohwnd** [comment]
Can merge as soon as it passes build.  If I don't ping me again :)

**Comment by mmitche** [comment]
@nohwnd Can you take a look at these failures?

**Comment by nohwnd** [comment]
Those tests break everytime there is any change in the output in the new version of SDK that we use to run the tests. Should be fixed now.

**Review by nohwnd — APPROVED** [review]

**Pull request merged**
