### PR TITLE
Updating package versions to the latest.

### PR DESCRIPTION
**Pull request by AbhitejJohn**

### CODE REVIEW

**Comment by singhsarab** [comment]
@AbhitejJohn The PR is failing.

**Comment by AbhitejJohn** [comment]
ah, the packages are checked in. I can fix that. 
Can these not be pulled from the nuget feed?

**Comment by singhsarab** [comment]
@AbhitejJohn These templates were supposed to be moved out to devdiv.
I am not sure where we are on that, at least that's what the last convo with Manish was.
For now let's just checkin the packages, because they are required for the offline scenario

**Comment by AbhitejJohn** [comment]
@singhsarab : This is now fixed. Can we get manual validation on this?

**Comment by singhsarab** [comment]
You will be doing that on the val build

**Comment by singhsarab** [comment]
Use this https://dev.azure.com/dnceng/internal/_build/results?buildId=430565

**Comment by singhsarab** [comment]
You'd be raising a PR on devdiv side for the insertion, that you should get validated.

**Comment by singhsarab** [comment]
@AbhitejJohn Have you inserted the templates? You should use this definition for the insertion https://dev.azure.com/dnceng/internal/_build/results?buildId=432801

**Pull request merged**
