### PR TITLE
Updated NUnit templates to use latest 4.2.0 version of the NUnit3TestAdapter

### PR DESCRIPTION
**Pull request by OsirisTerje**
New version of the adapter have been released.  Updating the templates.
Added NUnit.Analyzer package version 3.2.0 to the NUnit test templates.

### CODE REVIEW

**Comment by OsirisTerje** [comment]
@Sanan07 Hi!  Seems there is the same issue as last time.  Your package feed proxy have not been updated.  Can you get this running ?

**Comment by Haplois** [comment]
@OsirisTerje, thanks for the heads up! Looking into this. /cc: @nohwnd

**Comment by OsirisTerje** [comment]
@Sanan07 Ping :-)    This issue should be blocking a lot of work.  It seems your builds run off a package feed that is constantly not updated.  There should be no reason not to point directly to nuget.org, and thus resolve this once and for all.

**Comment by Haplois** [comment]
@OsirisTerje, sorry about this. I'll try to update and merge it today. (@cvpoienaru and I are maintaining this repo now.)

**Review by Haplois — APPROVED** [review]

**Pull request merged**
