### PR TITLE
Set copyright and package license

### PR DESCRIPTION
**Pull request by tmat**
Prepares repo for change https://github.com/dotnet/arcade/pull/2003 by setting `Copyright` and `PackageLicenseExpression` properties. These values will be required to be set by each repository once https://github.com/dotnet/arcade/pull/2003 is merged.

In order to not break the current builds this change sets the properties conditionally. This condition can be removed once all repos switch to Arcade that has https://github.com/dotnet/arcade/pull/2003.

@markwilkie

### CODE REVIEW

**Comment by singhsarab** [comment]
@tmat Can you please see why https://dev.azure.com/dnceng/public/_build?definitionId=308&_a=summary does not get triggered by default ?

**Comment by tmat** [comment]
IDK, @chcosta ?

**Comment by chcosta** [comment]
Looking at your build triggers...

- You have override the YAML pull request trigger from here.  This is not the reason builds are not triggering by default, but you probably don't need that checkbox.  Checking this box means that this section of your YAML is ignored...

```YAML
# CI and PR triggers
...
pr:
- master
```

- You have the "Only trigger builds for collaborator's pull request comments" checkbox enabled.  I think this is why you are not seeing builds get triggered by default.

**Comment by singhsarab** [comment]
@chcosta Thanks for recommendation
@tmat please merge these changes.

**Pull request merged**
