### PR TITLE
Updated NUnit templates to use adapter version 4.1.0

### PR DESCRIPTION
**Pull request by OsirisTerje**
A new version 4.1.0 of the NUnit3TestAdapter was released today.  This PR is for updating the NUnit templates to that version.

### CODE REVIEW

**Comment by Sanan07** [comment]
@OsirisTerje You also need to sync your new nuget packages with [dotnet-public feed](https://dev.azure.com/dnceng/public/_packaging?_a=package&feed=dotnet-public%40Local&package=NUnit3TestAdapter&protocolType=NuGet&version=4.0.0&view=versions)
Our pipeline downloads packages from there.
Last time I asked engineering team to manually sync with nuget.org, but maybe now is some automatic way to do it.

**Comment by OsirisTerje** [comment]
@Sanan07 Not sure if I have any rights to sync anything with your feed, but - if I can, please enlighten me :-)

**Comment by Sanan07** [comment]
Ok, I will try to ask the team to sync it.

**Comment by OsirisTerje** [comment]
Any progress on this ?

**Review by Sanan07 — APPROVED** [review]

**Pull request merged**
