### PR TITLE
Use PoolProvider for internal build

### PR DESCRIPTION
**Pull request by MattGal**

### CODE REVIEW

**Comment by MattGal** [comment]
@mmitche fYi

**Comment by singhsarab** [comment]
@MattGal Can you please explain what this change entails ? I thought this was the required change https://github.com/dotnet/test-templates/pull/63/files

**Comment by MattGal** [comment]
https://github.com/dotnet/test-templates/pull/63/files is necessary but not sufficient.  I've updated my change to have both changes now.    My change is needed because dotnet-internal-temp hasn't existed for some time now (if you have a build that uses this path, it's broken until this merges)

**Comment by singhsarab** [comment]
@MattGal The ci failed post your change, cam you please see if it is related to your change.

**Comment by MattGal** [comment]
@singhsarab no the failures are because of this:
```
:\workspace\_work\1\s\test\Microsoft.TestTemplates.AcceptanceTests\Microsoft.TestTemplates.AcceptanceTests.csproj : error NU3004: Package 'MSTest.TestFramework 1.3.2' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned. [F:\workspace\_work\1\s\test\Microsoft.TestTemplates.AcceptanceTests.sln]
F:\workspace\_work\1\s\test\Microsoft.TestTemplates.AcceptanceTests\Microsoft.TestTemplates.AcceptanceTests.csproj : error NU3004: Package 'MSTest.TestAdapter 1.3.2' from source 'https://api.nuget.org/v3/index.json': This repository indicated that all its packages are repository signed; however, this package is unsigned. [F:\workspace\_work\1\s\test\Microsoft.TestTemplates.AcceptanceTests.sln]
#
```
which is caused by this: https://github.com/dotnet/test-templates/blob/master/global.json#L6

... for giggles I'll update that too in my PR

**Comment by MattGal** [comment]
@singhsarab passed after I updated your .NET CLI.  Please merge at your leisure.

**Pull request merged**
