### PR TITLE
Fixed localization of templates

### PR DESCRIPTION
**Pull request by vlada-shubina**
https://github.com/dotnet/test-templates/pull/220 enabled localization only for one project. Enabled it also for others.

Please onboard repo to OneLocBuild to get the templates localized: https://aka.ms/AllAboutLoc

### CODE REVIEW

**Comment by Evangelink** [comment]
@vlada-shubina I don't know much about this change. Are you confident so I can merge "blindly"? Or shall I try to get feedback from someone else?

**Comment by Evangelink** [comment]
Ping @vlada-shubina

**Comment by vlada-shubina** [comment]
The change itself is safe, but you need to onboard the repo for localization.
The info is here: https://aka.ms/AllAboutLoc, you need to create ticket and loc people will get in touch. Please let them know that this is for templates localization.

**Comment by vlada-shubina** [comment]
@jonfortescue - do we need to do anything else from arcade standpoint for templates localization? `test-templates` is on arcade, and i see the scrips in the `eng` folder contain the logic for templates localization.

**Comment by Evangelink** [comment]
cc @cvpoienaru

**Comment by jonfortescue** [comment]
@vlada-shubina I think just making sure to add the [OneLocBuild template](https://github.com/dotnet/arcade/blob/main/Documentation/OneLocBuild.md) to the main pipeline would be it.

**Comment by Evangelink** [comment]
Closing as the PR is now totally outdated but we will use it as inspiration for the localization work now that we have properly onboarded to oneloc.

**Pull request closed without merging**
