### PR TITLE
Nunit3testadapter430

### PR DESCRIPTION
**Pull request by OsirisTerje**
* Updated NUnit3TestAdapter to version 4.3.0, which supports .net 7.  [Release notes](https://docs.nunit.org/articles/vs-test-adapter/AdapterV4-Release-Notes.html)
* Updated NUnit.Analyzers to version 3.5.0, which is the latest.

Ping @nohwnd 

A couple of questions:

1. @AbhitejJohn asked on another PR if you could automatically update these from the nuget feed.  Is that a way to go?  Right now also the coverlet is below and also the test.sdk, as far as I can see from a fresh new csproj:
image

3. If the version is replaced with a *, [floating version](https://learn.microsoft.com/en-us/nuget/concepts/package-versioning#floating-version-resolutions) that would bring in the correct version automatically, could that be an option ?  

Like: 
```csproj 
<PackageReference Include="NUnit3TestAdapter" Version="*" />
```

See #269 as an alternative PR with floating versions.

### CODE REVIEW

**Comment by OsirisTerje** [comment]
And I see that the build fails because your feed is not updated.

**Comment by nohwnd** [comment]
@OsirisTerje We are trying to update the versions less rather than more. We want to put a stable version that is proven to be working into those templates, once we ship them it takes a long time until enoung people start using them and then we don't have a real way of rolling back, unless we do servicing of dotnet/installer.

We should probably even remove net6.0, and netcoreapp3.1 templates from this repository, because those won't be updated unless we do servicing for those releases. The only versions that are now actively inserted are net7.0.2xx and net8.

I would prefer to not have floating versions, to avoid bringing a buggy version of adapters and test.sdk (not that you are producing them, but we should standardize across all packages in these templates, and that makes a bigger room for error).

**Comment by nohwnd** [comment]
@cvpoienaru can you please handle this update to the newest version of nunit? Please also update the new Playwright templates, there is PR pending that moves them to a different project that needs to be merged first. #267

**Comment by Evangelink** [comment]
I believe this PR can be closed as the content was done through PR #252

**Comment by Evangelink** [comment]
Closing this one, see previous comment.

**Pull request closed without merging**
